import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { resolve as resolvePath } from "node:path";
import type { Plugin } from "vite";

export interface DonghanhWidgetsOptions {
  /** Named widget entries. Key = widget name referenced by OperationConfig.widget. */
  entries: Record<string, string>;
  /** Output directory for widget HTML + manifest. Default: "dist/widgets". */
  outDir?: string;
  /** Manifest file name (written inside outDir). Default: "manifest.js". */
  manifestFile?: string;
  /** URI prefix. Default: "ui://widget/". */
  uriPrefix?: string;
  /** Shared CSP passed through to each widget. */
  csp?: {
    connectDomains?: string[];
    resourceDomains?: string[];
    frameDomains?: string[];
  };
  /** Shared sandbox domain. */
  domain?: string;
  /** Per-widget prefersBorder hint. */
  prefersBorder?: boolean;
}

interface WidgetManifestEntry {
  uri: string;
  html: string;
  domain?: string;
  csp?: DonghanhWidgetsOptions["csp"];
  prefersBorder?: boolean;
}

function hashShort(input: string): string {
  return createHash("sha256").update(input).digest("hex").slice(0, 10);
}

function buildHtml(name: string, js: string, css: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>${name}</title>
<style>body{margin:0;font-family:system-ui,-apple-system,sans-serif}${css}</style>
</head>
<body>
<div id="root"></div>
<script type="module">${js}</script>
</body>
</html>`;
}

/**
 * Vite plugin that bundles named widget entries into inline HTML + emits a
 * manifest module consumed by mcpRoutes.
 *
 * Each entry is built as a separate IIFE-style bundle (inlined), wrapped with
 * boilerplate HTML, and assigned a content-hashed URI. The generated manifest
 * exports a `widgets: Record<string, WidgetConfig>` compatible with
 * `@donghanh/hono` `mcpRoutes({ widgets })`.
 */
export function donghanhWidgets(opts: DonghanhWidgetsOptions): Plugin {
  const outDir = opts.outDir ?? "dist/widgets";
  const manifestFile = opts.manifestFile ?? "manifest.js";
  const uriPrefix = opts.uriPrefix ?? "ui://widget/";
  let root = "";

  return {
    name: "donghanh-widgets",
    apply: "build",

    config() {
      return {
        build: {
          rollupOptions: {
            input: { ...opts.entries },
            output: {
              entryFileNames: "assets/[name]-[hash].js",
              chunkFileNames: "assets/[name]-[hash].js",
              assetFileNames: "assets/[name]-[hash][extname]",
            },
          },
        },
      };
    },

    configResolved(config) {
      root = config.root;
    },

    async writeBundle(_options, bundle) {
      const manifest: Record<string, WidgetManifestEntry> = {};
      const absOut = resolvePath(root, outDir);
      await mkdir(absOut, { recursive: true });

      for (const name of Object.keys(opts.entries)) {
        const entryChunk = Object.values(bundle).find(
          (item) => item.type === "chunk" && item.isEntry && item.name === name,
        );
        if (!entryChunk || entryChunk.type !== "chunk") continue;

        const js = entryChunk.code;
        const cssFiles = entryChunk.viteMetadata?.importedCss ?? new Set();
        let css = "";
        for (const cssFile of cssFiles) {
          const asset = bundle[cssFile];
          if (asset && asset.type === "asset")
            css += `\n${asset.source.toString()}`;
        }

        const html = buildHtml(name, js, css);
        const hash = hashShort(html);
        const uri = `${uriPrefix}${name}-${hash}.html`;

        await writeFile(resolvePath(absOut, `${name}.html`), html, "utf8");

        manifest[name] = {
          uri,
          html,
          ...(opts.domain && { domain: opts.domain }),
          ...(opts.csp && { csp: opts.csp }),
          ...(opts.prefersBorder && { prefersBorder: true }),
        };
      }

      const manifestJs = `// generated by @donghanh/widget-vite — do not edit
export const widgets = ${JSON.stringify(manifest, null, 2)};
`;
      await writeFile(resolvePath(absOut, manifestFile), manifestJs, "utf8");
      const manifestDts = `// generated by @donghanh/widget-vite
import type { WidgetConfig } from "@donghanh/hono";
export declare const widgets: Record<string, WidgetConfig>;
`;
      await writeFile(
        resolvePath(absOut, manifestFile.replace(/\.js$/, ".d.ts")),
        manifestDts,
        "utf8",
      );
    },
  };
}

export default donghanhWidgets;
