name = "donghanh-site"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/client"
binding = "ASSETS"
